DROP TABLE TAQUERIAS;

CREATE TABLE TAQUERIAS (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  "NAME" VARCHAR(128) NOT NULL, 
  RATING INTEGER NOT NULL, 
  USER_ID INTEGER NOT NULL,
  UNIQUE ("NAME"),
  PRIMARY KEY (ID)--,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

INSERT INTO TAQUERIAS ("NAME", RATING, USER_ID) VALUES 
    ('Changos Taqueria', 5, 1),
    ('Torchy''s Tacos', 4, 2),
    ('Taco Deli', 5, 3),
    ('Taco Bell', 2, 1),
    ('Fuzzy''s Taco Shop', 4, 2),
    ('Taco Cabana', 2, 3),
    ('Cabo Bob''s', 3, 4);
